### ISSUE TITLE
When doing Attention Cropping, Randomly choose attention map or just choose first attention map?

### ISSUE THREAD

**Issue by genausz** [GuYuc/WS-DAN.PyTorch#11]
As paper described:
> For each training image, we randomly choose one of its attention map A k to guide the data augmentation process,

attention map are randomly choosed. but in code:
`crop_images = batch_augment(X, attention_map[:, :1, :, :], mode='crop', theta=(0.4, 0.6), padding_ratio=0.1)`
only use the first attention map?
Thanks.

**Comment by GuYuc** [comment]
@genausz here the shape of attention_map is (B, 2, H, W), these two attention maps was already randomly chosen in network, see models/wsdan.py for details.
