### ISSUE TITLE
eval

### ISSUE THREAD

**Issue by yujialele** [GuYuc/WS-DAN.PyTorch#13]
您好，我想问您一下，在您的eval 代码中我如何可以显示每一个attention map的热图。

**Comment by GuYuc** [comment]
@yujialele 您好，抱歉现在才回复您。config.py最下面有一栏Eval Config的参数，您可以通过将visualize设为True，eval_ckpt指定为你的模型保存地址，eval_savepath指定为一个文件夹。然后，在运行python eval.py的过程中，会将所有输出热图保存至eval_savepath指定的文件夹里。每张图片会有三张对应图片保存下来，在README的Attention Maps Visualization部分有说明，您也可以修改eval里面的代码实现自己想要的效果。
