### ISSUE TITLE
evel

### ISSUE THREAD

**Issue by boxyao** [GuYuc/WS-DAN.PyTorch#14]
self.corrects * 100. 为什么要给self.corrects 乘100呢？

**Comment by GuYuc** [comment]
@WangLuyao-Yi 感谢你的提问，很抱歉现在才回答你的问题。我没有找到我的代码里面有self.corrects * 100这个操作，但如果你指的是输入到self.fc的feature有x100的这个操作的话，这个操作是论文作者在官方实现里为了加速训练过程引入的一个trick，issue #1 里面有提到。
