### ISSUE TITLE
some question about Augmentation Map in paper.

### ISSUE THREAD

**Issue by XGuider** [GuYuc/WS-DAN.PyTorch#16]
![image](https://user-images.githubusercontent.com/19531010/80982722-48f04f80-8e5e-11ea-9d25-15f31e4ff71e.png)
normalize it as k th Augmentation Map not found in your code.?
Last,thnx you best work!

**Comment by XGuider** [comment]
![image](https://user-images.githubusercontent.com/19531010/80983161-d764d100-8e5e-11ea-901d-5d3099eb5135.png) and this code make me confused.Hope you could reply .

**Comment by GuYuc** [comment]
@XGuider Hi. Such normalization step was combined with threshold segmentation, which are equally processed as segmenting the map by using (threshold x max value of this map), see line:151-153 in utils.py.
