### ISSUE TITLE
when I run train.py, there is the problem, request to solve.

### ISSUE THREAD

**Issue by 5Yesterday** [GuYuc/WS-DAN.PyTorch#18]
feature_center_batch = F.normalize(feature_center[y], dim=-1)
IndexError: tensors used as indices must be long, byte or bool tensors

**Comment by Boatsure** [comment]
it's about numpy version, the y in feature_center[y] is wrong type. Check your dataset class and the type of label it returns. 
In my case, change
`img = self.transforms(img);
        label = np.int32(splits[1])  # splits is one line in txt;
        return data.float(), label;`
to
`img = self.transforms(img);
        label = np.int64(splits[1])  # splits is one line in txt;
        return data.float(), label;` 
works

**Comment by 5Yesterday** [comment]
> it's about numpy version, the y in feature_center[y] is wrong type. Check your dataset class and the type of label it returns.
> In my case, change
> `img = self.transforms(img); label = np.int32(splits[1]) # splits is one line in txt; return data.float(), label;`
> to
> `img = self.transforms(img); label = np.int64(splits[1]) # splits is one line in txt; return data.float(), label;`
> works

ok, thanks, I will have a try.
