### ISSUE TITLE
resnet50在cub上只达到了84.7%的acc

### ISSUE THREAD

**Issue by Javacr** [GuYuc/WS-DAN.PyTorch#19]
在使用resnet50作为backbone时，在cub数据集上只达到了84.7%的acc。

**Comment by Javacr** [comment]
今天试了一下inception作为特征提取网络，能达到87.7%

**Comment by GuYuc** [comment]
@Javacr 这篇文章好像用的都是inception，可以深入比较一下各种feature extractor在这个问题上的区别
