### ISSUE TITLE
What's the meaning of  Val Acc (0.53, 2.60)?

### ISSUE THREAD

**Issue by albert0713** [GuYuc/WS-DAN.PyTorch#24]
When I train the model with Standford Car, it shows  'Val Acc (0.53, 2.60)'. What are 0.53 and 2.60 meaning for? Thank you

**Comment by GuYuc** [comment]
It means top-1 and top-5 accuracy multiplied by 100 (0.53% and 2.60%), you may set topk parameters in TopKAccuracyMetric(topk=(1, 5)) to get any top-x accuracy
