### ISSUE TITLE
Some confusions about the code

### ISSUE THREAD

**Issue by ShihuaHuang95** [GuYuc/WS-DAN.PyTorch#4]
Hi, many thanks for this implementation. As shown in the following figure1, Does it mean the k (shown in the figure2) in the original always equal to 0 during training? 
![image](https://user-images.githubusercontent.com/36783415/61276716-2152cc80-a7e3-11e9-8d93-a2bb8b1ec115.png)
![image](https://user-images.githubusercontent.com/36783415/61276873-7e4e8280-a7e3-11e9-957d-43135eab10f2.png)

**Comment by GuYuc** [comment]
@Hshihua Hi, crop_mask was upsampled from attention_map with size of (B, 1, H, W), which means the network only output a single attention map, so the index must be 0 here. The random selection (in training phase) or average reduction (in testing phase) was done inside the network module. Feel free to try some other ways to implement this operation if you want.
