### ISSUE TITLE
self.features=inception_v3(pretrained=True).get_features() dimension dismatch?

### ISSUE THREAD

**Issue by wangtao2668129173** [GuYuc/WS-DAN.PyTorch#8]
excese me,l would like test inception.py,input 3x229x229,and output 3x17x17,it's the shape I need,but
in wsdan.py ,input 3x229x229,awesome!output 3x12x12?thank

**Comment by GuYuc** [comment]
@wangtao2668129173 Your input should be 299 instead of 229
