### ISSUE TITLE
 epoch_acc[0] += accuracy(y_pred, y, topk=(1, 3, 5))

### ISSUE THREAD

**Issue by wangtao2668129173** [GuYuc/WS-DAN.PyTorch#9]
1，3，5代表什么
1，3，5代表什么

l don't understand What does 1, 3, 5 stand for?Why to define epoch+acc=np.array([[0,0,0],[0,0,0],[0,0,0]])

**Comment by GuYuc** [comment]
@wangtao2668129173 Hi, topk=(1,3,5) means our accuracy() returns top-1, top-3, and top-5 accuracy in an np.array() with size (3,). You may set topk=(1,) if you want top-1 accuracy only.
